---
application:
  name: "easyrtc-server"
  project: "easyrtc-server"
  organization: "QoveryCommunity"
routers:
- name: "main-easyrtc-server"
  routes:
  - application_name: "easyrtc-server"
    paths:
    - "/*"
